### ISSUE TITLE
数据库优化思路

### ISSUE THREAD

**Issue by liueleven** [0voice/interview_internal_reference#13]
2）应尽量避免在 where 子句中对字段进行 null 值判断，否则将导致引擎放弃使用索引而进行全表扫描，如： select id from t where num is null 可以在num上设置默认值0，确保表中num列没有null值，然后这样查询： select id from t where num=0

--------------------分割线-------------------------------
不是非我杠精，关于null,isNull,isNotNull其实是要看成本的，是否回表等因素总和考虑，才会决定是要走索引还是走全表扫描

也给大家找了一个作者的[博文](https://mp.weixin.qq.com/s/CEJFsDBizdl0SvugGX7UmQ)，仅供参考！！！

**Comment by zhiyong0804** [comment]
根据你的评论提交了个commit，见[79d09](https://github.com/0voice/interview_internal_reference/commit/b7088e02fe145c1c4908410e043d58c3c4b79d09)
