### ISSUE TITLE
不知道为什么自从上次被国外程序员吐槽github被中文侵占后，开始抵触这类awesome类的仓库

### ISSUE THREAD

**Issue by baiyutang** [0voice/interview_internal_reference#17]
是否要反思，我们技术圈都关注些什么？

**Comment by ijkzen** [comment]
反思个屁，我学别人的知识，有门槛，我就跨过门槛，学习英语再去学；我学有所成，想要分享我的知识，既然是我的知识，以何种方式表达，是我的自由，你看不看得懂，与我何干！

**Comment by ijkzen** [comment]
套用国防部发言人吴谦的话：
> 西方总是喜欢炒作中国码农正当合法的代码提交，依我看这主要是心态没有调整好，心病还没有治好。也许是因为以往中国代码提交的过少了，那么今后我们多提交几次，西方习惯了，也就好了。

**Comment by baiyutang** [comment]
> 套用国防部发言人吴谦的话：
> 
> > 西方总是喜欢炒作中国码农正当合法的代码提交，依我看这主要是心态没有调整好，心病还没有治好。也许是因为以往中国代码提交的过少了，那么今后我们多提交几次，西方习惯了，也就好了。

可以。每个人思维的角度不同。

**Comment by cl773915148** [comment]
个人想法：需求决定我们关注的方向，面经这类源于国内从业人员生活压力大， 国外这方面困扰较小，较为关注技术本身，确实值得学习。但是就分享技术、经验来说，并没有高低贵贱之分。

**Comment by blwinner12** [comment]
国内IT从业人员压力非常大，竞争很激烈，国外就不一样，我同学西安交大计算机系，作为交换生到加拿大，毕业找不到工作，又去了意大利也找不到工作，因为岗位非常非常少，没有市场需求，最后去的美国找到的工作。再者面经客观上的确可以提升新人的综合水平，面试题目也有很多代表了当前技术潮流，多看大公司的面经可以拓宽眼界。

**Comment by baiyutang** [comment]
> 个人想法：需求决定我们关注的方向，面经这类源于国内从业人员生活压力大， 国外这方面困扰较小，较为关注技术本身，确实值得学习。但是就分享技术、经验来说，并没有高低贵贱之分。

在理。开源精神可嘉

**Comment by xuhongda** [comment]
做这种重复项目意义何在？而且泄露别人的题目真的好吗，批判！！！鄙视！！！

**Comment by EtoDemerzel0427** [comment]
> 做这种重复项目意义何在？而且泄露别人的题目真的好吗，批判！！！鄙视！！！

建议下次写邮件批判leetcode创始人一番。

**Comment by huluBrother** [comment]
他是想表达我国企业面试造航母，进去拧螺丝这种现象还是单纯抵制中国企业？是批评我们把关注点过多放在面试题上而不是技术上，还是只是批评我们中国人的分享？来，把那份吐槽地址贴出来

**Comment by baiyutang** [comment]
> 他是想表达我国企业面试造航母，进去拧螺丝这种现象还是单纯抵制中国企业？是批评我们把关注点过多放在面试题上而不是技术上，还是只是批评我们中国人的分享？来，把那份吐槽地址贴出来

找到了一个相关的

https://juejin.im/entry/5d3442c66fb9a07ead5a36b8/  [InfoQ] 中国人霸榜 GitHub Trending，国外开发者很无奈

**Comment by huluBrother** [comment]
> > 他是想表达我国企业面试造航母，进去拧螺丝这种现象还是单纯抵制中国企业？是批评我们把关注点过多放在面试题上而不是技术上，还是只是批评我们中国人的分享？来，把那份吐槽地址贴出来
> 
> 找到了一个相关的
> 
> https://juejin.im/entry/5d3442c66fb9a07ead5a36b8/ [InfoQ] 中国人霸榜 GitHub Trending，国外开发者很无奈

我还以为在国外论坛上吐槽呢，中国的那部分媒体没有说使用中文就是犯罪就已经很给面子了
