### ISSUE TITLE
1.1.9 答案完善

### ISSUE THREAD

**Issue by keytouch** [0voice/interview_internal_reference#33]
#9 里面提得非常详细，原文我觉得应该要修改一下
再者，还要考虑对应网卡是否是多路访问网络

ping目标ip时，先查路由表，确定出接口
- 如果落在直连接口子网内，此时若为以太网等 _多路访问网络_ 则先查询arp缓存，命中则直接发出，否则在该接口上发arp询问目标ip的mac地址，取得后发出，若为ppp等 _点对点网络_ ，则直接可以发出；
- 如果查表落在缺省路由上，此时若为以太网等 _多路访问网络_ 则先查询网关arp缓存，命中则直接发出，否则在该接口上发arp询问网关的mac地址，取得后发出，若为ppp等 _点对点网络_ ，则直接可以发出；
- 若查表未命中，则返回不可达。

**Comment by jiaoqiyuan** [comment]
可以提交 pull requests

**Comment by keytouch** [comment]
fixed
