### ISSUE TITLE
1.1.3 思路完善

### ISSUE THREAD

**Issue by 63isOK** [0voice/interview_internal_reference#58]
BST(二叉搜索树)在wiki中已经有详细的描述了，下面陈述一下我个人的思路：
对于bst的搜索，有两种常用的编码实现，递归和迭代。对于普通的通过key来查找，
递归和迭代都很容易实现，如果添加一个影响因子(比如说通过key查找的同时，还要满足父节点的value是多少...)，这样通过递归实现，也就是添加一个参数，函数体里添加一个逻辑即可，但对于迭代来说，实现的复杂度就增加了很多。本例就是一个典型，所以这题推荐使用递归实现，主要因为递归实现难度不高。

下面分析一下，本题用递归实现的方式。(从不同的角度看问题，就有不同的解决方案)

-----

求bst第k小的节点？  

角度1：也就是示例中的解法，我用自己的语言翻译一遍：如果存在某个节点n，她的左子树中节点的个数是k-1,那么这个节点n就是要找的节点。此时会存在3种情况：(bingo，左子树节点个数正好是k-1;左子树节点数大于k-1,那么以节点n的左子节点为基础，重新找;左子树的节点数小于k-1,说明要找的节点在节点n的右子树上，以n的右子节点为基础，继续查找，此时k因子也会有响应的调整)，这种解法，我称为"多次左子树遍历"

角度2：基于bst的特性，中序遍历的结果，取第k个节点，就是问题的解，这种解法，我称为"中序遍历 + 计数"

两种解法的对比：
- 两者都是基于递归来实现
- 多次左子树遍历，会存在多次遍历; 中序+计数的方式则不会，对性能有要求的，可以选择后一种解法

**Comment by 63isOK** [comment]
示例中的c++代码也是有缺失的，最大的问题是没有写明如何统计左子树的节点个数，所有的val变量都源自递归函数，递归函数里没有赋值的地方。

所以关于文字描述部分是可取的，而代码部分是没有验证的。

如果按照示例的思路发展，会从"多次左子树遍历+统计"慢慢演变到"前序+计数"。不管咋样，角度1都是一个新的角度，让我思考颇多。

**Comment by 63isOK** [comment]
我用go写了一个基准测试(只使用基本数据结构，未优化)，最后的结果如下：

bst退化后，"多次左子树遍历+统计" 和 "前序+计数"，两者的表现基本相差不大(前者的效率甚至略高一点)。

非退化情况，后者的效率会明显比前者高很多。

bst从退化到平衡，两者的效率差甚至呈指数关系。

**Comment by 63isOK** [comment]
测试例子在[这儿](https://github.com/63isOK/interview/)

**Comment by wangbojing** [comment]
可以贡献到master。

**Comment by 63isOK** [comment]
好的，我会尽快新建pr

**Comment by 63isOK** [comment]
@wangbojing 已提交pr，可以开始reivew

**Comment by xiexu2008** [comment]
> BST(二叉搜索树)在wiki中已经有详细的描述了，下面陈述一下我个人的思路：
> 对于bst的搜索，有两种常用的编码实现，递归和迭代。对于普通的通过key来查找，
> 递归和迭代都很容易实现，如果添加一个影响因子(比如说通过key查找的同时，还要满足父节点的value是多少...)，这样通过递归实现，也就是添加一个参数，函数体里添加一个逻辑即可，但对于迭代来说，实现的复杂度就增加了很多。本例就是一个典型，所以这题推荐使用递归实现，主要因为递归实现难度不高。
> 
> 下面分析一下，本题用递归实现的方式。(从不同的角度看问题，就有不同的解决方案)
> 
> 求bst第k小的节点？
> 
> 角度1：也就是示例中的解法，我用自己的语言翻译一遍：如果存在某个节点n，她的左子树中节点的个数是k-1,那么这个节点n就是要找的节点。此时会存在3种情况：(bingo，左子树节点个数正好是k-1;左子树节点数大于k-1,那么以节点n的左子节点为基础，重新找;左子树的节点数小于k-1,说明要找的节点在节点n的右子树上，以n的右子节点为基础，继续查找，此时k因子也会有响应的调整)，这种解法，我称为"多次左子树遍历"
> 
> 角度2：基于bst的特性，前序遍历的结果，取第k个节点，就是问题的解，这种解法，我称为"前序遍历 + 计数"
> 
> 两种解法的对比：
> 
> * 两者都是基于递归来实现
> * 多次左子树遍历，会存在多次遍历; 前序+计数的方式则不会，对性能有要求的，可以选择后一种解法

为什么是”前序“，不应该是”中序遍历 + 计数“吗？

**Comment by 63isOK** [comment]
多谢，确实是中序遍历(左 根 右)
