### ISSUE TITLE
标题确定没问题？

### ISSUE THREAD

**Issue by zhanghba** [0voice/interview_internal_reference#8]
![image](https://user-images.githubusercontent.com/35982572/61351553-997dc880-a89d-11e9-93a1-6dc4e1b64686.png)

**Comment by zhiyong0804** [comment]
可以继续详细点不，这样我们才能讨论下去，或者才能更新？不过事实上我不认为这个标题有问题， 欢迎继续留言讨论。  :)

**Comment by zhanghba** [comment]
连接的“惊群“，而不是集群吗？

**Comment by chilejiang1024** [comment]
[惊群效应](https://www.zhihu.com/question/22756773)

**Comment by zhanghba** [comment]
多谢 @chilejiang1024 @zhiyong0804 
学习到了~
