### ISSUE TITLE
1.1.9 输入 ping IP 后敲回车，发包前会发生什么？这题回答讲的不明白

### ISSUE THREAD

**Issue by zboya** [0voice/interview_internal_reference#9]
ping目标ip时，如果在相同网段直接先查询arp缓存，如果找到目标ip的mac地址，直接发送出去，如果缓存中查不到，则从相同网段的网卡发arp问目标ip的mac地址，拿到mac地址后发送出去。如果不在主机的网段里，会查询默认网关ip，接着查询arp缓存，是否有网关的mac地址记录，如果有，填充该mac地址，发送出去，如果没有，发arp问网关的mac地址，得到结果，发送出去。

**Comment by zhiyong0804** [comment]
看了你的评论，我觉得原文很清晰的，如果还有异议，我们一起讨论。
